# Generated by Django 4.1.13 on 2024-06-28 05:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient_recipie_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipie_image_file_path),
        ),
    ]
